package supersurveys

import org.codehaus.groovy.grails.test.support.ControllerNameExtractor;

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def filters = {
        all(controller:"*", action:"*") {
            before = {
				// Si on est dans le controleur "accout" ou "user"
				// on bloque l'accès aux non identifiés
                if (controllerName != "account" || controllerName != "user") return true

                // Access control by convention.
                accessControl()
            }
        }
    }
}
